### ISSUE TITLE
Uncaught Error: This socket is closed.

### ISSUE THREAD

**Issue by djpowers** [AtomLinter/linter-erb#5]
1. In an .html.erb file, I added an ERB tag (`<% %>`), and began typing a conditional within it (only typed "if @" before the error was triggered).
2. It seemed to simultaneously trigger https://github.com/atom/atom/issues/5507 as well. Both errors were triggered upon entering the "@" character. Seems similar to https://github.com/AtomLinter/linter-erb/issues/4.

**Atom Version**: 0.190.0
**System**: Mac OS X 10.9.5
**Thrown From**: [linter-erb](https://github.com/AtomLinter/linter-erb) package, v0.1.0

### Stack Trace

Uncaught Error: This socket is closed.

```
At events.js:141

Error: This socket is closed.
  at Socket._writeGeneric (net.js:634:19)
  at Socket._write (net.js:687:8)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at Socket.Writable.write (_stream_writable.js:210:11)
  at Socket.write (net.js:612:40)
  at erbStdout (/Users/dpowers/.atom/packages/linter-erb/lib/linter-erb.coffee:65:33)
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:137:13)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)

```

### Commands

```
     -1:13.3 editor:move-to-end-of-screen-line (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:12.3 key-binding-resolver:toggle (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:09.9 core:move-up (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:04.6 key-binding-resolver:toggle (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:01.5 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:00.9 core:save (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:41.5 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:41.1 editor:select-to-first-character-of-line (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:40.8 core:select-up (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:39.9 core:cut (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:39.1 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:38.6 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:37.8 core:save (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:07.5 vim-mode:insert-below-with-newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:03.1 snippets:next-tab-stop (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:03.1 snippets:expand (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "whitespace",
      "linter-scss-lint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.9.0
color-picker, v1.6.0
linter, v0.12.0
linter-coffeelint, v0.2.1
linter-erb, v0.1.0
linter-jshint, v0.1.2
linter-ruby, v0.1.4
minimap, v4.7.6
vim-mode, v0.43.0

# Dev
No dev packages
```

**Comment by djpowers** [comment]
I have not seen this error in quite some time, so I believe it has been resolved (possibly in atom/notifications#62). I can no longer reproduce the problem, but I'll reopen if I see it again.

**Comment by kWhittington** [comment]
Hi, I started getting the same error. Do you think this is related to your earlier problem?

1. Opened existing .erb file:
```erb
<% if model.attribute %>
  <%= link_to path_helper(model),
              class: 'btn btn-primary' do %>
    <%= fa_icon_tag 'fa-download',
                    data: {
                      title: 'download',
                      placement: 'right'
                    } %>
  <% end %>
<% else %>
  <%= link_to '#',
              class: 'btn btn-primary disabled' do %>
    <%= fa_icon_tag 'fa-download muted',
                    data: {
                      title: 'no download',
                      placement: 'right'
                    } %>
  <% end %>
<% end %>
```

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-erb](https://github.com/AtomLinter/linter-erb) package, v0.1.1


### Stack Trace

Uncaught Error: This socket is closed.

```
At events.js:141

Error: This socket is closed.
  at Socket._writeGeneric (net.js:634:19)
  at Socket._write (net.js:687:8)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at Socket.Writable.write (_stream_writable.js:210:11)
  at Socket.write (net.js:612:40)
  at /Users/kwhittin/.atom/packages/linter-erb/lib/linter-erb.coffee:58:33
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:85:13)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)

```

### Commands

```
     -0:40.4.0 blur (div.settings-view.pane-item)
     -0:39.4.0 core:save (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  3x -0:33.6.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:32.9.0 core:undo (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:32.3.0 pane:show-next-item (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  3x -0:32.3.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:23.7.0 pane:show-previous-item (div.settings-view.pane-item)
     -0:23.7.0 blur (div.settings-view.pane-item)
     -0:23.2.0 core:save (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  3x -0:18.6.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  4x -0:05.4.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:04.6.0 pane:show-next-item (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:04.5.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:04.1.0 pane:show-previous-item (div.settings-view.pane-item)
     -0:04.1.0 blur (div.settings-view.pane-item)
     -0:03.7.0 core:save (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "isotope-ui",
      "afterglow-like"
    ],
    "disabledPackages": [
      "symbols-view",
      "autocomplete-ruby"
    ]
  },
  "linter-erb": {
    "rubyOnRailsMode": true,
    "erbExecutablePath": "/Users/kwhittin/.rvm/rubies/ruby-2.1.5/bin/erb"
  }
}
```

### Installed Packages

```coffee
# User
afterglow-like, v0.2.1
atom-beautify, v0.28.4
atom-ctags, v4.1.2
atom-pair, v1.1.6
autocomplete-clang, v0.7.0
autocomplete-paths, v1.0.2
ctags-status, v1.3.1
isotope-ui, v2.4.0
language-gitignore, v0.2.0
linter, v0.12.7
linter-erb, v0.1.1
linter-rubocop, v0.2.7
motepair, v0.20.0
pretty-json, v0.3.3
vim-mode, v0.53.0
vim-surround, v0.6.1

# Dev
No dev packages
```

**Comment by THPubs** [comment]
I can confirm that the error is still there and the linter is not working because of it.

**Comment by andrefreitas** [comment]
Any updates on this?

**Comment by dimascyriaco** [comment]
Been having this problem too.

**Comment by Arcanemagus** [comment]
Marking this as closed, the linter needs a complete re-write before it will ever run.
